### ISSUE TITLE
Use of reserved word "package"

### ISSUE THREAD

**Issue by Bytooo** [peterthehan/create-discord-bot#19]
In the top index.js:13 the **reserved** word **package** is being declared as a constant variable.

JavaScript reserved words shouldn't be used as variables, labels, or function names I suggest it being rename to _package or something similar.

**Comment by peterthehan** [comment]
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Lexical_grammar#Keywords

TIL. I'll swap it with a better name.

**Comment by peterthehan** [comment]
Fixed in https://github.com/peterthehan/create-discord-bot/pull/24, closing.
