### ISSUE TITLE
TypeScript Support on the Utility

### ISSUE THREAD

**Issue by Bytooo** [peterthehan/create-discord-bot#25]
TypeScript has recently surpassed Python in most loved languages. With its popularity rising each day I think it would be good plus to have TypeScript support for the whole project.

For the bot files I'm thinking it could be added as a setup question a simple yes or no that would serve all the .js files as .ts (_of course after making sure the files right now are compatible with TypeScript out of the box)_

I would also recommend converting the whole project into TypeScript since its mind-blowing how awesome TypeScript is, but I'm unaware if @peterthehan is familiar with TypeScript.

**Comment by peterthehan** [comment]
I'm not familiar with ts, but I've been looking for a reason to pick it up and this would certainly be a good opportunity. I'll start chipping away at this in my free time.

**Comment by Bytooo** [comment]
Sounds good! I'm decent at it so I'll start developing this feature too.

**Comment by peterthehan** [comment]
Hey, I had to revert this code because the utility script was breaking (`npx peterthehan/create-discord-bot`). Something involving the shebang, `ts-node`, and `bin` in `package.json` was being uncooperative. I tried to push a quick fix to `master` to no avail and I thought it was going to take longer to figure out than I realized which forced my hand.

In hindsight, I should have ran `npx shadowtime2000/create-discord-bot#typescript` to test.

**Comment by shadowtime2000** [comment]
I don't understand why it didn't work if the `bin` is set to `ts-node src/index.ts`

**Comment by shadowtime2000** [comment]
@peterthehan There are some issues on using a shebang with `ts-node` [ts-node#995](https://github.com/TypeStrong/ts-node/issues/995) something like that could work.

**Comment by peterthehan** [comment]
I don't think `bin` supports commands, I think it's only files. I tried a variety of shebangs like: ts-node and ts-node-script...

**Comment by peterthehan** [comment]
> ts-node-script is, indeed, the recommended entrypoint because it locates a tsconfig relative to the location of the script, not to cwd.

Ah, if I'm interpreting this right, maybe it's not able to locate tsconfig since it's working in `src/` while tsconfig is in root.

**Comment by shadowtime2000** [comment]
So one problem would be using a command in `bin`. I will look into solutions tomorrow but could you delete the breaking code revert commits in `typescript` @peterthehan ?

**Comment by shadowtime2000** [comment]
One solution to check out would be to use a `cli-bootstrap` recommended in [ts-node#995](https://github.com/TypeStrong/ts-node/issues/995)

**Comment by peterthehan** [comment]
Ah right that screws up the feature branch. I'm in bed now but I'll do it first thing in the morning.

Out of curiosity, is there a viable solution that steps around using ts-node and instead just does tsc && node?

**Comment by shadowtime2000** [comment]
I believe shebangs only allow one command as a binary but we could probably write a workaround with a shell script or something to run both.

**Comment by peterthehan** [comment]
Reverted `typescript` branch back to right when your changes were merged. Feel free to open a new PR.

**Comment by shadowtime2000** [comment]
Hmm using a shebang with `ts-node-script` seems to work for me on the Git bash for Windows.

**Comment by shadowtime2000** [comment]
@peterthehan @Bytooo Since we are going through the route of committing build files do you think we should connect a service to auto build and commit?

**Comment by Bytooo** [comment]
It's just till we find a better solution so I don't think we need to automate deployment yet

**Comment by peterthehan** [comment]
Should be doable via a GitHub action but for now I agree with Bytooo here. If it appears to be a longer term solution than imagined we can implement something like what shadow suggested.
