### ISSUE TITLE
Install QOL dev dependencies on the bot

### ISSUE THREAD

**Issue by peterthehan** [peterthehan/create-discord-bot#27]
https://github.com/peterthehan/create-discord-bot/pull/20 some good ideas came from this PR. Prettier and nodemon would be nice.

**Comment by shadowtime2000** [comment]
What about `eslint` and `tslint`?

**Comment by peterthehan** [comment]
eslint seems to be the recommended linter (tslint appears to have been deprecated). Works for me.

**Comment by shadowtime2000** [comment]
We could also let them install the `eslint` plugins to work with Typescript.

**Comment by peterthehan** [comment]
After some thought, gonna switch gears and take the opinionated approach and add these qol deps by default.
1. Lot of the bot design is already opinionated
2. Avoid adding additional complexity to the utility script
3. The aforementioned dev deps are pretty darn convenient
