### ISSUE TITLE
TypeScript Support on the core bot files

### ISSUE THREAD

**Issue by peterthehan** [peterthehan/create-discord-bot#41]

**Comment by shadowtime2000** [comment]
I can start working on this one once #36 is merged.

**Comment by shadowtime2000** [comment]
I guess I will start working on this now but I will target to merge it into the `typescript` branch.

**Comment by peterthehan** [comment]
Sure, @Bytooo was last working on tests for the utility so there should be no dependencies between these 2 issues.

**Comment by peterthehan** [comment]
Will be resolved with #90
