### ISSUE TITLE
Run npx against the ts code instead of the compiled code

### ISSUE THREAD

**Issue by peterthehan** [peterthehan/create-discord-bot#60]
Today, we are pushing the compiled code (in `dist/`) to the repo so that npx can run this code using the shebang + bin value in package.json. It would be great to instead run the ts code directly with npx so we can stop pushing build files.

**Comment by shadowtime2000** [comment]
One way I can think of is programmatically compiling typescript and then running it. The other is to require users to have `ts-node` and `typescript` installed.

**Comment by peterthehan** [comment]
Yup some of these came up as potential solutions in that initial ts conversion PR. I was against the user requiring packages to run the npx script in favor of it just working out of the box, so something along the lines of the former would be preferred.

**Comment by peterthehan** [comment]
I was thinking over the problem we're trying to solve, at least in regards to the 2 solutions we're mulling over - compile at runtime and execute vs execute precompiled file, I think I actually prefer the latter (what we already have).

Pros:
1. Less code we need to add to do this runtime compile step (both our earlier unsuccessful PRs)
2. Smaller dependencies means faster npx start up = better UX

Cons:
1. We have to push `dist/`

Off the top of my head, pros outweigh the cons here imo. Curious to hear what you think.

**Comment by shadowtime2000** [comment]
As far as I have tried and seen, it is actually impossible to compile and execute because it modifies the program files from within the program which you can't really do.

**Comment by shadowtime2000** [comment]
Another solution would be to just not use Typescript for the utility script and only use it for the core bot files and the command widget, because using Typescript in that will affect the user more, though I don't see that as a solution we would really want.

**Comment by peterthehan** [comment]
I suppose that's another option.

I'm okay keeping this as is considering everything we've discussed. I don't think we're gonna get anywhere on this so unless you have objections, I'll close this issue

**Comment by shadowtime2000** [comment]
You can close the issue then.
