### ISSUE TITLE
Change copy/update logic in utility script to fetch from template repo

### ISSUE THREAD

**Issue by peterthehan** [peterthehan/create-discord-bot#69]
In an effort to decouple this repo's utility script from the template bot, a new repo was created https://github.com/peterthehan/discord-bot to house the template bot code.

We should delete the files under `app/` from this repo, and update the copy/update logic in the utility to fetch the files from the new repo. We should delete the `.git/` folder that will result from the clone.

Note: may get #53 for free

**Comment by shadowtime2000** [comment]
I was thinking, we could try using something like `degit` to download it instead of Git cloning, because we don't have to delete the `.git` folder and the user gets source control already set up.

**Comment by peterthehan** [comment]
Looks like it covers our usecase pretty well.

**Comment by shadowtime2000** [comment]
Which would be faster? Running `npx degit` or just using the `degit` module. I think the module but I don't know.

**Comment by peterthehan** [comment]
Probably nearly the same, either case requires us to download the module, whether it's run cli or programmatically, and I'm assuming the codebase is identical between the two. Leaning towards module.

**Comment by peterthehan** [comment]
Client library over at: https://github.com/peterthehan/discord-bot-core-client

No longer needed.
