### ISSUE TITLE
JSDoc For Typescript

### ISSUE THREAD

**Issue by shadowtime2000** [peterthehan/create-discord-bot#72]
Currently, we commit `dist` files with compiled Typescript. Typescript has support for static typing using JSDoc comments which can allow us to not have to have any build process. An example of a project using that is [SwordCSS](https://github.com/swordcss/swordcss).

**Comment by shadowtime2000** [comment]
@peterthehan @Bytooo Thoughts?

**Comment by peterthehan** [comment]
This might be a good alternative since we were never able to solve the build issue with npx.

**Comment by Bytooo** [comment]
Yeah agree, if this makes it so we don't have to push the dist folder then we should do it.
