### ISSUE TITLE
Error starting with nom start

### ISSUE THREAD

**Issue by Daniellop1** [peterthehan/create-discord-bot#75]
Hi there, I'm trying to start the project but an error appeared in the console.
I let the error in the following link -> https://pastebin.com/sLf38GnB

**Comment by peterthehan** [comment]
Hmm the logs in the pastebin aren't very descriptive, mind including what you see in terminal? Also, feel free to drop by the server (in readme) for a quicker troubleshooting turnaround time.

**Comment by peterthehan** [comment]
Closing since no response. Again, feel free to drop by the server for troubleshooting if you still need it.
