### ISSUE TITLE
Add logic to aggregate Intents from widgets to pass as args when initializing Client

### ISSUE THREAD

**Issue by peterthehan** [peterthehan/create-discord-bot#77]
Intents will be mandatory when discord.js switches from gateway v6 -> v8 and/or Discord kills v6. https://discord.com/developers/docs/topics/gateway#privileged-intents

Simple fix would be to initialize the client enabling all intents https://discord.js.org/#/docs/main/master/class/Intents?scrollTo=s-ALL

Better implementation would be to add a list of necessary intents as a configuration option for each widget so that we're receiving events for only the things each respective widget requires.

**Comment by peterthehan** [comment]
https://stackoverflow.com/questions/64559390/none-of-my-discord-js-guildmember-events-are-emitting-my-user-caches-are-basica Useful tldr to get up to speed.

**Comment by shadowtime2000** [comment]
A `config.js` file in every widget could do this, and then we could think about injecting global dependencies with that file too, #73.

**Comment by peterthehan** [comment]
Will be resolved with #90.
