### ISSUE TITLE
Add slash commands widget

### ISSUE THREAD

**Issue by peterthehan** [peterthehan/create-discord-bot#80]
https://discord.com/developers/docs/interactions/slash-commands, need to see if usecases are covered.

**Comment by shadowtime2000** [comment]
I think it may be better to hold off on this because most bots (or at least the ones I have used) still have there own command parsing and stuff. @peterthehan Are you suggesting a feature built into the core part of it, or a new command widget which uses thhese slash commands?

**Comment by peterthehan** [comment]
On second thought, probably leaning towards another widget instead of replacing outright. I have a bunch of non-conventional commands as well, and I'm not entirely sure slash commands would cover the bases w/o doing some research. Mostly adding this issue to keep track of this new feature.

Will edit title.

**Comment by peterthehan** [comment]
I'm thinking when all is said and done, the current command widget could be spun off into its own repo while we make the slash command widget the default widget that comes with the install.

**Comment by peterthehan** [comment]
Not in the scope of this repo, closing.
