### ISSUE TITLE
Command categories | Suggestion

### ISSUE THREAD

**Issue by TheEdaL06** [peterthehan/create-discord-bot#81]
Hi there, I'm COÐΣ THΣΣÐAL ツᴮᴼᵀ#8126 and I would like to suggest an option or something that makes your commands in categories like Moderation, General, Fun, etc.

```
 bot-name
 |---src
      |---commands
            |--General
                  |---userinfo
                  |---serverinfo
            |---Fun
                  |---Memes
                  |--Kiss
```

Something like I did up there

**Comment by peterthehan** [comment]
I'm not too keen on coupling command categories to the file structure of the commands folder. Adding a new field to the CommandBuilder would be preferable so that it can be programmatic.

**Comment by peterthehan** [comment]
Not in the scope of this repo once #90 is merged, closing.
