### ISSUE TITLE
Invalid inline type syntax

### ISSUE THREAD

**Issue by Bytooo** [peterthehan/create-discord-bot#82]
https://github.com/peterthehan/create-discord-bot/blob/dcb3d541636aea80c7c67fe07243a654ca09e5fb/src/index.js#L11

1. The code above is marked as an invalid type annotation (at least for me). I suggest changing it to `* @typedef {function():void} action`

https://github.com/peterthehan/create-discord-bot/blob/dcb3d541636aea80c7c67fe07243a654ca09e5fb/src/index.js#L27

2. And changing the code above to `* @property {action} action` to match _change 1_ and prevent warnings like the following: _"Assigned expression type {action: action, message: string, ignoreDry: boolean}[] is not assignable to type Step[]"_

**Comment by peterthehan** [comment]
Resolved with #90
