### ISSUE TITLE
Error message

### ISSUE THREAD

**Issue by Yasser-Alshinawah** [peterthehan/create-discord-bot#85]
Everytime I do npx peterthehan/create-discord-bot I get this error message:
npm ERR! code ENOENT
npm ERR! syscall spawn git
npm ERR! path git
npm ERR! errno -4058
npm ERR! enoent Error while executing:
npm ERR! enoent undefined ls-remote -h -t ssh://git@github.com/peterthehan/create-discord-bot.git
npm ERR! enoent
npm ERR! enoent
npm ERR! enoent spawn git ENOENT
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\yasse\AppData\Roaming\npm-cache\_logs\2021-04-21T20_35_32_703Z-debug.log

**Comment by peterthehan** [comment]
You might not have git installed, can you check what version you have with `git --version`?

If you're still having issues, you can drop by the discord server for more help.

**Comment by Yasser-Alshinawah** [comment]
Yeah I didn’t have Git installed so I installed it and did it but once it got to after the name and bot token it gave me an error saying my bot token didn’t work I verified it twice

**Comment by Yasser-Alshinawah** [comment]
Sorry for being so late I just checked my emails

**Comment by peterthehan** [comment]
The token error message isn't a blocker to the template project generation, you can always go into the generated project and edit the token value in the `/.env` file if necessary.

**Comment by Yasser-Alshinawah** [comment]
Ok

**Comment by Yasser-Alshinawah** [comment]
Hey so I got everything the widgets and stuff but how would I run the bot since I got everything except I don't know how to run it I would usually have a run.bat that I would just open but this one doesn't have one so I have no idea how to run the bot

**Comment by peterthehan** [comment]
When the `npx` command completes, it instructs you to navigate to the newly created directory and run `npm start`.

**Comment by Yasser-Alshinawah** [comment]
would I have to reinstall it since when I do that in the Console it says start file missing/not found

**Comment by Yasser-Alshinawah** [comment]
also whats the defualt prefix for the bot

**Comment by peterthehan** [comment]
You need node (you can check via `node -v`). You can find the command widget config under `/src/widgets/command/config.json`. Default prefix is either mentioning the bot or using `.` e.g. `@bot ping` or `.ping`

Might be easier to communicate over discord.

**Comment by Yasser-Alshinawah** [comment]
I do have node

**Comment by Yasser-Alshinawah** [comment]
ok let me try

**Comment by Yasser-Alshinawah** [comment]
whats ur Discord Btw
I'll add you

**Comment by peterthehan** [comment]
Please visit the server, it's linked at the bottom of the readme.

**Comment by Yasser-Alshinawah** [comment]
ok
