### ISSUE TITLE
NPX command Not working.

### ISSUE THREAD

**Issue by Opticz1400** [peterthehan/create-discord-bot#86]
Hello. I just found this and was going through the steps and cant seem to get the NPX command to work. It doesn't make the utility nor does it make or edit anything. Am I missing anything or is this outdated?

**Comment by peterthehan** [comment]
Check if you have node/npm installed, https://github.com/peterthehan/create-discord-bot#troubleshooting

**Comment by Opticz1400** [comment]
I ended up just installing Git Bash. Bot runs and commands work but cannot get the reaction role widget to work.

**Comment by peterthehan** [comment]
Closing since resolved.
